import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@wrappers/theme-provider'
import AuthProvider from '@components/wrappers/auth-provider'
import WithAuth from '@components/wrappers/withAuth'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <AuthProvider>
            <WithAuth>
              {children}
            </WithAuth>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
